package com.example.module_hot.bean.list_songs

data class Privilege(
    val chargeInfoList: List<ChargeInfo>,
    val code: Int,
    val cp: Int,
    val cs: Boolean,
    val dl: Int,
    val dlLevel: String,
    val dlLevels: Any,
    val downloadMaxBrLevel: String,
    val downloadMaxbr: Int,
    val fee: Int,
    val fl: Int,
    val flLevel: String,
    val flag: Int,
    val freeTrialPrivilege: FreeTrialPrivilege,
    val id: Long,
    val ignoreCache: Any,
    val maxBrLevel: String,
    val maxbr: Int,
    val message: Any,
    val payed: Int,
    val pl: Int,
    val plLevel: String,
    val plLevels: Any,
    val playMaxBrLevel: String,
    val playMaxbr: Int,
    val preSell: Boolean,
    val rightSource: Int,
    val rscl: Int,
    val sp: Int,
    val st: Int,
    val subp: Int,
    val toast: Boolean
)